name: citizenwallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  go_router: ^6.5.6
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6
  path: ^1.8.2
  flutter_svg: ^2.0.4
  intl: ^0.18.0
  web3dart: ^2.6.1
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  convert: ^3.1.1
  flutter:
    sdk: flutter
  lottie: ^2.3.2
  mobile_scanner: ^3.2.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - .env
    - assets/wallet.svg
    - assets/icons/profile.svg
    - assets/data/native_chains.json
    - assets/data/chains.json
    - assets/lottie/success.json
    - assets/lottie/app.json
    - assets/lottie/wallet_loader.json
    - assets/lottie/wallet_receive.json
  uses-material-design: false
